name: Build AngelScript

on:
  push:
    tags:
      - "v*"

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        submodules: recursive
        lfs: false
    
    - name: Build AngelScript
      shell: cmd
      run: build.bat
    
    - name: Get version
      id: version
      run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ steps.version.outputs.VERSION }}
    
    - name: Upload lib
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./build/Release/angelscript.lib
        asset_name: angelscript.lib
        asset_content_type: application/octet-stream
    #- name: Upload pdb
    #  uses: actions/upload-release-asset@v1
    #  env:
    #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #  with:
    #    upload_url: ${{ steps.create_release.outputs.upload_url }}
    #    asset_path: ./build/Release/angelscript.pdb
    #    asset_name: angelscript.pdb
    #    asset_content_type: application/octet-stream
